version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    entrypoint: 
      - bash
      - -c
    ports:
      - 3000:3000
    command: 
      - node ./app.js
  automation:
    image: cypress/included:cypress-12.17.3-node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
    depends_on: 
      - app
    volumes:
      - ./cypress:/cypress 
      - ./cypress.config.js:/cypress.config.js
    
